# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usable_points',
            field=models.IntegerField(default=0),
        ),
    ]
